// Copyright 2021-2025 Zenauth Ltd.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: authzen/authorization/v1/svc.proto

package authorizationv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/cerbos/cerbos/api/genpb/authzen/authorization/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AuthorizationServiceName is the fully-qualified name of the AuthorizationService service.
	AuthorizationServiceName = "authzen.authorization.v1.AuthorizationService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AuthorizationServiceEvaluateProcedure is the fully-qualified name of the AuthorizationService's
	// Evaluate RPC.
	AuthorizationServiceEvaluateProcedure = "/authzen.authorization.v1.AuthorizationService/Evaluate"
)

// AuthorizationServiceClient is a client for the authzen.authorization.v1.AuthorizationService
// service.
type AuthorizationServiceClient interface {
	// Evaluate performs an access evaluation
	Evaluate(context.Context, *connect.Request[v1.EvaluationRequest]) (*connect.Response[v1.EvaluationResponse], error)
}

// NewAuthorizationServiceClient constructs a client for the
// authzen.authorization.v1.AuthorizationService service. By default, it uses the Connect protocol
// with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To
// use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb()
// options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAuthorizationServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AuthorizationServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	authorizationServiceMethods := v1.File_authzen_authorization_v1_svc_proto.Services().ByName("AuthorizationService").Methods()
	return &authorizationServiceClient{
		evaluate: connect.NewClient[v1.EvaluationRequest, v1.EvaluationResponse](
			httpClient,
			baseURL+AuthorizationServiceEvaluateProcedure,
			connect.WithSchema(authorizationServiceMethods.ByName("Evaluate")),
			connect.WithClientOptions(opts...),
		),
	}
}

// authorizationServiceClient implements AuthorizationServiceClient.
type authorizationServiceClient struct {
	evaluate *connect.Client[v1.EvaluationRequest, v1.EvaluationResponse]
}

// Evaluate calls authzen.authorization.v1.AuthorizationService.Evaluate.
func (c *authorizationServiceClient) Evaluate(ctx context.Context, req *connect.Request[v1.EvaluationRequest]) (*connect.Response[v1.EvaluationResponse], error) {
	return c.evaluate.CallUnary(ctx, req)
}

// AuthorizationServiceHandler is an implementation of the
// authzen.authorization.v1.AuthorizationService service.
type AuthorizationServiceHandler interface {
	// Evaluate performs an access evaluation
	Evaluate(context.Context, *connect.Request[v1.EvaluationRequest]) (*connect.Response[v1.EvaluationResponse], error)
}

// NewAuthorizationServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAuthorizationServiceHandler(svc AuthorizationServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	authorizationServiceMethods := v1.File_authzen_authorization_v1_svc_proto.Services().ByName("AuthorizationService").Methods()
	authorizationServiceEvaluateHandler := connect.NewUnaryHandler(
		AuthorizationServiceEvaluateProcedure,
		svc.Evaluate,
		connect.WithSchema(authorizationServiceMethods.ByName("Evaluate")),
		connect.WithHandlerOptions(opts...),
	)
	return "/authzen.authorization.v1.AuthorizationService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AuthorizationServiceEvaluateProcedure:
			authorizationServiceEvaluateHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAuthorizationServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAuthorizationServiceHandler struct{}

func (UnimplementedAuthorizationServiceHandler) Evaluate(context.Context, *connect.Request[v1.EvaluationRequest]) (*connect.Response[v1.EvaluationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("authzen.authorization.v1.AuthorizationService.Evaluate is not implemented"))
}
