// Code generated by protoc-gen-go-hashpb. DO NOT EDIT.
// protoc-gen-go-hashpb v0.4.2

package authorizationv1

import (
	protowire "google.golang.org/protobuf/encoding/protowire"
	structpb "google.golang.org/protobuf/types/known/structpb"
	hash "hash"
	maps "maps"
	math "math"
	slices "slices"
	unsafe "unsafe"
)

func authzen_authorization_v1_EvaluationRequest_Action_hashpb_sum(m *EvaluationRequest_Action, hasher hash.Hash, ignore map[string]struct{}) {
	if _, ok := ignore["authzen.authorization.v1.EvaluationRequest.Action.name"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(nil, uint64(len(m.GetName()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetName()), len(m.GetName())))
	}
	if _, ok := ignore["authzen.authorization.v1.EvaluationRequest.Action.properties"]; !ok {
		if len(m.Properties) > 0 {
			for _, k := range slices.Sorted(maps.Keys(m.Properties)) {
				_, _ = hasher.Write(protowire.AppendVarint(nil, uint64(len(k))))
				_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(k), len(k)))
				if m.Properties[k] != nil {
					google_protobuf_Value_hashpb_sum(m.Properties[k], hasher, ignore)
				}
			}
		}
	}
}

func authzen_authorization_v1_EvaluationRequest_Resource_hashpb_sum(m *EvaluationRequest_Resource, hasher hash.Hash, ignore map[string]struct{}) {
	if _, ok := ignore["authzen.authorization.v1.EvaluationRequest.Resource.type"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(nil, uint64(len(m.GetType()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetType()), len(m.GetType())))
	}
	if _, ok := ignore["authzen.authorization.v1.EvaluationRequest.Resource.id"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(nil, uint64(len(m.GetId()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetId()), len(m.GetId())))
	}
	if _, ok := ignore["authzen.authorization.v1.EvaluationRequest.Resource.properties"]; !ok {
		if len(m.Properties) > 0 {
			for _, k := range slices.Sorted(maps.Keys(m.Properties)) {
				_, _ = hasher.Write(protowire.AppendVarint(nil, uint64(len(k))))
				_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(k), len(k)))
				if m.Properties[k] != nil {
					google_protobuf_Value_hashpb_sum(m.Properties[k], hasher, ignore)
				}
			}
		}
	}
}

func authzen_authorization_v1_EvaluationRequest_Subject_hashpb_sum(m *EvaluationRequest_Subject, hasher hash.Hash, ignore map[string]struct{}) {
	if _, ok := ignore["authzen.authorization.v1.EvaluationRequest.Subject.type"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(nil, uint64(len(m.GetType()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetType()), len(m.GetType())))
	}
	if _, ok := ignore["authzen.authorization.v1.EvaluationRequest.Subject.id"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(nil, uint64(len(m.GetId()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetId()), len(m.GetId())))
	}
	if _, ok := ignore["authzen.authorization.v1.EvaluationRequest.Subject.properties"]; !ok {
		if len(m.Properties) > 0 {
			for _, k := range slices.Sorted(maps.Keys(m.Properties)) {
				_, _ = hasher.Write(protowire.AppendVarint(nil, uint64(len(k))))
				_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(k), len(k)))
				if m.Properties[k] != nil {
					google_protobuf_Value_hashpb_sum(m.Properties[k], hasher, ignore)
				}
			}
		}
	}
}

func authzen_authorization_v1_EvaluationRequest_hashpb_sum(m *EvaluationRequest, hasher hash.Hash, ignore map[string]struct{}) {
	if _, ok := ignore["authzen.authorization.v1.EvaluationRequest.subject"]; !ok {
		if m.GetSubject() != nil {
			authzen_authorization_v1_EvaluationRequest_Subject_hashpb_sum(m.GetSubject(), hasher, ignore)
		}
	}
	if _, ok := ignore["authzen.authorization.v1.EvaluationRequest.resource"]; !ok {
		if m.GetResource() != nil {
			authzen_authorization_v1_EvaluationRequest_Resource_hashpb_sum(m.GetResource(), hasher, ignore)
		}
	}
	if _, ok := ignore["authzen.authorization.v1.EvaluationRequest.action"]; !ok {
		if m.GetAction() != nil {
			authzen_authorization_v1_EvaluationRequest_Action_hashpb_sum(m.GetAction(), hasher, ignore)
		}
	}
	if _, ok := ignore["authzen.authorization.v1.EvaluationRequest.context"]; !ok {
		if len(m.Context) > 0 {
			for _, k := range slices.Sorted(maps.Keys(m.Context)) {
				_, _ = hasher.Write(protowire.AppendVarint(nil, uint64(len(k))))
				_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(k), len(k)))
				if m.Context[k] != nil {
					google_protobuf_Value_hashpb_sum(m.Context[k], hasher, ignore)
				}
			}
		}
	}
}

func authzen_authorization_v1_EvaluationResponse_Context_Reason_hashpb_sum(m *EvaluationResponse_Context_Reason, hasher hash.Hash, ignore map[string]struct{}) {
	if _, ok := ignore["authzen.authorization.v1.EvaluationResponse.Context.Reason.properties"]; !ok {
		if len(m.Properties) > 0 {
			for _, k := range slices.Sorted(maps.Keys(m.Properties)) {
				_, _ = hasher.Write(protowire.AppendVarint(nil, uint64(len(k))))
				_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(k), len(k)))
				if m.Properties[k] != nil {
					google_protobuf_Value_hashpb_sum(m.Properties[k], hasher, ignore)
				}
			}
		}
	}
}

func authzen_authorization_v1_EvaluationResponse_Context_hashpb_sum(m *EvaluationResponse_Context, hasher hash.Hash, ignore map[string]struct{}) {
	if _, ok := ignore["authzen.authorization.v1.EvaluationResponse.Context.id"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(nil, uint64(len(m.GetId()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetId()), len(m.GetId())))
	}
	if _, ok := ignore["authzen.authorization.v1.EvaluationResponse.Context.reason_admin"]; !ok {
		if m.GetReasonAdmin() != nil {
			authzen_authorization_v1_EvaluationResponse_Context_Reason_hashpb_sum(m.GetReasonAdmin(), hasher, ignore)
		}
	}
	if _, ok := ignore["authzen.authorization.v1.EvaluationResponse.Context.reason_user"]; !ok {
		if m.GetReasonUser() != nil {
			authzen_authorization_v1_EvaluationResponse_Context_Reason_hashpb_sum(m.GetReasonUser(), hasher, ignore)
		}
	}
}

func authzen_authorization_v1_EvaluationResponse_hashpb_sum(m *EvaluationResponse, hasher hash.Hash, ignore map[string]struct{}) {
	if _, ok := ignore["authzen.authorization.v1.EvaluationResponse.decision"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(nil, protowire.EncodeBool(m.GetDecision())))
	}
	if _, ok := ignore["authzen.authorization.v1.EvaluationResponse.context"]; !ok {
		if m.GetContext() != nil {
			authzen_authorization_v1_EvaluationResponse_Context_hashpb_sum(m.GetContext(), hasher, ignore)
		}
	}
}

func google_protobuf_ListValue_hashpb_sum(m *structpb.ListValue, hasher hash.Hash, ignore map[string]struct{}) {
	if _, ok := ignore["google.protobuf.ListValue.values"]; !ok {
		if len(m.Values) > 0 {
			for _, v := range m.Values {
				if v != nil {
					google_protobuf_Value_hashpb_sum(v, hasher, ignore)
				}
			}
		}
	}
}

func google_protobuf_Struct_hashpb_sum(m *structpb.Struct, hasher hash.Hash, ignore map[string]struct{}) {
	if _, ok := ignore["google.protobuf.Struct.fields"]; !ok {
		if len(m.Fields) > 0 {
			for _, k := range slices.Sorted(maps.Keys(m.Fields)) {
				_, _ = hasher.Write(protowire.AppendVarint(nil, uint64(len(k))))
				_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(k), len(k)))
				if m.Fields[k] != nil {
					google_protobuf_Value_hashpb_sum(m.Fields[k], hasher, ignore)
				}
			}
		}
	}
}

func google_protobuf_Value_hashpb_sum(m *structpb.Value, hasher hash.Hash, ignore map[string]struct{}) {
	if m.Kind != nil {
		if _, ok := ignore["google.protobuf.Value.kind"]; !ok {
			switch t := m.Kind.(type) {
			case *structpb.Value_NullValue:
				_, _ = hasher.Write(protowire.AppendVarint(nil, uint64(t.NullValue)))
			case *structpb.Value_NumberValue:
				_, _ = hasher.Write(protowire.AppendFixed64(nil, math.Float64bits(t.NumberValue)))
			case *structpb.Value_StringValue:
				_, _ = hasher.Write(protowire.AppendVarint(nil, uint64(len(t.StringValue))))
				_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(t.StringValue), len(t.StringValue)))
			case *structpb.Value_BoolValue:
				_, _ = hasher.Write(protowire.AppendVarint(nil, protowire.EncodeBool(t.BoolValue)))
			case *structpb.Value_StructValue:
				if t.StructValue != nil {
					google_protobuf_Struct_hashpb_sum(t.StructValue, hasher, ignore)
				}
			case *structpb.Value_ListValue:
				if t.ListValue != nil {
					google_protobuf_ListValue_hashpb_sum(t.ListValue, hasher, ignore)
				}
			}
		}
	}
}
